CREATE TABLE "site_visits" (
	"id" serial PRIMARY KEY NOT NULL,
	"site_location_id" integer NOT NULL,
	"guest_session_id" integer,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"phone" text,
	"email" text,
	"company" text,
	"vehicle_plate" text,
	"purpose" text,
	"expected_duration_minutes" integer,
	"host_type" text NOT NULL,
	"host_partner_id" integer,
	"host_vendor_id" integer,
	"check_in_time" timestamp with time zone DEFAULT now() NOT NULL,
	"check_in_latitude" double precision,
	"check_in_longitude" double precision,
	"check_out_time" timestamp with time zone,
	"check_out_latitude" double precision,
	"check_out_longitude" double precision,
	"auto_checked_out" boolean DEFAULT false NOT NULL,
	"safety_acknowledged_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone
);