CREATE TABLE "tickets" (
	"id" serial PRIMARY KEY NOT NULL,
	"site_location_id" integer NOT NULL,
	"vendor_id" integer NOT NULL,
	"field_employee_id" integer,
	"work_type_id" integer NOT NULL,
	"status" text DEFAULT 'initiated' NOT NULL,
	"intake_channel" text DEFAULT 'partner_self_service' NOT NULL,
	"description" text,
	"notes" text,
	"kickback_reason" text,
	"check_in_time" timestamp with time zone,
	"check_out_time" timestamp with time zone,
	"check_in_latitude" double precision,
	"check_in_longitude" double precision,
	"check_out_latitude" double precision,
	"check_out_longitude" double precision,
	"lifecycle_state" text,
	"en_route_at" timestamp with time zone,
	"on_location_at" timestamp with time zone,
	"on_location_latitude" double precision,
	"on_location_longitude" double precision,
	"arrived_at" timestamp with time zone,
	"departure_latitude" double precision,
	"departure_longitude" double precision,
	"starting_mileage" numeric(10, 1),
	"ending_mileage" numeric(10, 1),
	"unlocked_at" timestamp with time zone,
	"unlocked_by_id" integer,
	"unlock_count" integer DEFAULT 0 NOT NULL,
	"created_by_id" integer,
	"closed_by_id" integer,
	"closed_at" timestamp with time zone,
	"pre_cancel_status" text,
	"cancelled_at" timestamp with time zone,
	"cancelled_by_id" integer,
	"scheduled_start_at" timestamp with time zone,
	"scheduled_duration_minutes" integer,
	"foreman_user_id" integer,
	"scheduled_at" timestamp with time zone,
	"scheduled_by_id" integer,
	"late_check_in_reminder_sent_at" timestamp with time zone,
	"approved_at" timestamp with time zone,
	"payment_method" text,
	"payment_reference" text,
	"payment_note" text,
	"payment_dispersed_at" timestamp with time zone,
	"payment_dispersed_by_id" integer,
	"payment_receipt_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);