CREATE TABLE "vendor_people" (
	"id" serial PRIMARY KEY NOT NULL,
	"vendor_id" integer NOT NULL,
	"vendor_role" text DEFAULT 'office' NOT NULL,
	"roles" text[] DEFAULT '{}' NOT NULL,
	"job_title" text,
	"first_name" text NOT NULL,
	"last_name" text DEFAULT '' NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"pec_certification" boolean DEFAULT false NOT NULL,
	"pec_expiration_date" date,
	"photo_url" text,
	"profile_photo_path" text,
	"hourly_rate" numeric(8, 2),
	"rate_kind" text DEFAULT 'hourly' NOT NULL,
	"daily_rate" numeric(10, 2),
	"user_id" integer,
	"invite_token" text,
	"invite_sent_at" timestamp with time zone,
	"preferred_language" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" text,
	CONSTRAINT "vendor_people_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "vendor_people_invite_token_unique" UNIQUE("invite_token")
);