CREATE TABLE "tax_1099_filings" (
	"id" serial PRIMARY KEY NOT NULL,
	"tax_year" integer NOT NULL,
	"form_type" text NOT NULL,
	"payer_partner_id" integer NOT NULL,
	"recipient_vendor_id" integer NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"filing_method" text DEFAULT 'manual' NOT NULL,
	"corrected_status" text DEFAULT 'none' NOT NULL,
	"original_payee_snapshot" jsonb,
	"external_reference" text,
	"filed_at" timestamp with time zone,
	"delivered_at" timestamp with time zone,
	"delivery_channel" text,
	"notes" text,
	"sendgrid_message_id" text,
	"last_event_type" text,
	"last_event_at" timestamp with time zone,
	"bounce_reason" text,
	"opened_at" timestamp with time zone,
	"updated_by_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);