CREATE TABLE "notification_preferences" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"tickets_enabled" boolean DEFAULT true NOT NULL,
	"hotlist_enabled" boolean DEFAULT true NOT NULL,
	"compliance_enabled" boolean DEFAULT true NOT NULL,
	"crew_enabled" boolean DEFAULT true NOT NULL,
	"system_enabled" boolean DEFAULT true NOT NULL,
	"visitor_enabled" boolean DEFAULT true NOT NULL,
	"push_enabled" boolean DEFAULT true NOT NULL,
	"dnd_start_hour" integer,
	"dnd_end_hour" integer,
	"qb_bulk_expiry_in_app_enabled" boolean DEFAULT true NOT NULL,
	"qb_bulk_expiry_email_enabled" boolean DEFAULT true NOT NULL,
	"tickets_email_enabled" boolean DEFAULT true NOT NULL,
	"hotlist_email_enabled" boolean DEFAULT true NOT NULL,
	"compliance_email_enabled" boolean DEFAULT true NOT NULL,
	"crew_email_enabled" boolean DEFAULT false NOT NULL,
	"system_email_enabled" boolean DEFAULT false NOT NULL,
	"visitor_email_enabled" boolean DEFAULT false NOT NULL,
	"email_digest_enabled" boolean DEFAULT false NOT NULL,
	"comments_enabled" boolean DEFAULT true NOT NULL,
	"comment_mention_email_enabled" boolean DEFAULT true NOT NULL,
	"comment_reply_email_enabled" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);