CREATE TABLE "vendors" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"contact_name" text NOT NULL,
	"contact_email" text NOT NULL,
	"contact_phone" text,
	"physical_address" text,
	"billing_address" text,
	"operating_radius_miles" integer,
	"latitude" double precision,
	"longitude" double precision,
	"geocoded_at" timestamp with time zone,
	"state_tax_id" text,
	"federal_tax_id" text,
	"business_phone" text,
	"hours_of_operation" text,
	"blurb" text,
	"logo_url" text,
	"logo_square_url" text,
	"brand_primary_color" text,
	"brand_accent_color" text,
	"daily_ot_hours" numeric(5, 2),
	"weekly_ot_hours" numeric(5, 2),
	"overtime_multiplier" numeric(4, 2),
	"insurance_carrier" text,
	"insurance_policy_number" text,
	"insurance_expiration_date" text,
	"coi_document_url" text,
	"wc_carrier" text,
	"wc_policy_number" text,
	"wc_expiration_date" text,
	"wc_document_url" text,
	"gl_carrier" text,
	"gl_policy_number" text,
	"gl_expiration_date" text,
	"gl_document_url" text,
	"auto_liability_carrier" text,
	"auto_liability_policy_number" text,
	"auto_liability_expiration_date" text,
	"auto_liability_document_url" text,
	"w9_document_url" text,
	"w9_last_updated_at" timestamp with time zone,
	"current_catalog_version_id" integer,
	"catalog_authority_attested_at" timestamp with time zone,
	"catalog_authority_attested_by_user_id" integer,
	"aging_threshold_days" jsonb DEFAULT '[1,15,30]'::jsonb NOT NULL,
	"e_delivery_consent" boolean DEFAULT false NOT NULL,
	"e_delivery_consent_at" timestamp with time zone,
	"e_delivery_email" text,
	"accounting_failure_notifications_enabled" boolean DEFAULT true NOT NULL,
	"accounting_reconciliation_notifications_enabled" boolean DEFAULT false NOT NULL,
	"accounting_reconciliation_digest_cadence" text DEFAULT 'per_push' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);