CREATE INDEX "reconciliation_weekly_recap_log_vendor_idx" ON "reconciliation_weekly_recap_log" USING btree ("vendor_id");
CREATE UNIQUE INDEX "reconciliation_weekly_recap_log_dedupe_unique" ON "reconciliation_weekly_recap_log" USING btree ("dedupe_key");
CREATE INDEX "vendor_merge_audit_survivor_idx" ON "vendor_merge_audit_log" USING btree ("survivor_vendor_id","created_at");
CREATE INDEX "vendor_merge_audit_created_idx" ON "vendor_merge_audit_log" USING btree ("created_at");
CREATE INDEX "site_location_admin_audit_site_idx" ON "site_location_admin_audit_log" USING btree ("site_location_id","created_at");
CREATE INDEX "site_location_admin_audit_created_idx" ON "site_location_admin_audit_log" USING btree ("created_at");
CREATE INDEX "schedule_cert_override_audit_ticket_idx" ON "schedule_cert_override_audit_log" USING btree ("ticket_id","created_at");
CREATE INDEX "schedule_cert_override_audit_created_idx" ON "schedule_cert_override_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "qb_account_mapping_scope_line_type" ON "qb_account_mapping" USING btree ("vendor_id","partner_id","line_type");
CREATE INDEX "qb_account_mapping_audit_created_idx" ON "qb_account_mapping_audit_log" USING btree ("created_at");
CREATE INDEX "qb_account_mapping_audit_line_type_idx" ON "qb_account_mapping_audit_log" USING btree ("line_type","created_at");
CREATE INDEX "qb_account_mapping_audit_vendor_idx" ON "qb_account_mapping_audit_log" USING btree ("vendor_id","created_at");
CREATE INDEX "qb_account_mapping_audit_partner_idx" ON "qb_account_mapping_audit_log" USING btree ("partner_id","created_at");
CREATE INDEX "qb_account_mapping_audit_actor_idx" ON "qb_account_mapping_audit_log" USING btree ("actor_user_id","created_at");
CREATE INDEX "qb_account_mapping_bulk_actions_created_idx" ON "qb_account_mapping_bulk_actions" USING btree ("created_at");
CREATE INDEX "qb_account_mapping_cleanup_audit_created_idx" ON "qb_account_mapping_cleanup_audit" USING btree ("created_at");
CREATE UNIQUE INDEX "tax_1099_filings_unique" ON "tax_1099_filings" USING btree ("tax_year","form_type","payer_partner_id","recipient_vendor_id");
CREATE INDEX "tax_1099_filings_year_idx" ON "tax_1099_filings" USING btree ("tax_year","form_type");
CREATE INDEX "tax_1099_filings_payer_idx" ON "tax_1099_filings" USING btree ("payer_partner_id","tax_year");
CREATE INDEX "tax_1099_filings_sendgrid_msg_idx" ON "tax_1099_filings" USING btree ("sendgrid_message_id");
CREATE INDEX "tax_1099_correction_audit_filing_idx" ON "tax_1099_correction_audit_log" USING btree ("filing_id","created_at");
CREATE INDEX "tax_1099_correction_audit_created_idx" ON "tax_1099_correction_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "signup_assistant_counters_ns_key_uniq" ON "signup_assistant_counters" USING btree ("namespace","key");