CREATE INDEX "direct_assignments_vendor_status_idx" ON "direct_assignments" USING btree ("vendor_id","status");
CREATE INDEX "direct_assignments_partner_status_idx" ON "direct_assignments" USING btree ("partner_id","status");
CREATE INDEX "direct_assignments_site_idx" ON "direct_assignments" USING btree ("site_location_id");
CREATE INDEX "field_push_tokens_user_idx" ON "field_push_tokens" USING btree ("user_id");
CREATE INDEX "fire_transmitter_settings_audit_created_idx" ON "fire_transmitter_settings_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "onboarding_progress_partner_uniq" ON "onboarding_progress" USING btree ("partner_id");
CREATE UNIQUE INDEX "onboarding_progress_vendor_uniq" ON "onboarding_progress" USING btree ("vendor_id");
CREATE UNIQUE INDEX "onboarding_progress_vendor_people_uniq" ON "onboarding_progress" USING btree ("vendor_people_id");
CREATE UNIQUE INDEX "partners_canonical_name_unique" ON "partners" USING btree (lower(btrim("name")));
CREATE INDEX "platform_settings_audit_field_created_idx" ON "platform_settings_audit_log" USING btree ("field","created_at");
CREATE UNIQUE INDEX "vendors_canonical_name_unique" ON "vendors" USING btree (lower(btrim("name")));
CREATE UNIQUE INDEX "work_types_canonical_name_unique" ON "work_types" USING btree (lower(btrim("name")));
CREATE UNIQUE INDEX "vendor_work_types_vendor_work_type_unique" ON "vendor_work_types" USING btree ("vendor_id","work_type_id");
CREATE UNIQUE INDEX "vendor_catalog_versions_vendor_version_unique" ON "vendor_catalog_versions" USING btree ("vendor_id","version");
CREATE INDEX "vendor_catalog_versions_vendor_idx" ON "vendor_catalog_versions" USING btree ("vendor_id");
CREATE INDEX "partner_eula_acceptances_pair_idx" ON "partner_eula_acceptances" USING btree ("partner_id","vendor_id","vendor_catalog_version_id");
CREATE INDEX "partner_vendor_approval_events_pair_idx" ON "partner_vendor_approval_events" USING btree ("partner_id","vendor_id","created_at");
CREATE INDEX "partner_vendor_approval_events_vendor_idx" ON "partner_vendor_approval_events" USING btree ("vendor_id");
CREATE UNIQUE INDEX "work_type_site_location_unique" ON "work_type_site_locations" USING btree ("work_type_id","site_location_id");
CREATE UNIQUE INDEX "partner_work_type_afe_unique" ON "partner_work_type_afes" USING btree ("partner_id","work_type_id");
CREATE UNIQUE INDEX "partner_vendor_work_type_approval_unique" ON "partner_vendor_work_type_approvals" USING btree ("partner_id","vendor_id","work_type_id");
CREATE UNIQUE INDEX "partner_vendor_relationship_unique" ON "partner_vendor_relationships" USING btree ("partner_id","vendor_id");
CREATE UNIQUE INDEX "vendor_site_location_afe_unique" ON "vendor_site_location_afes" USING btree ("vendor_id","site_location_id");
CREATE UNIQUE INDEX "site_locations_partner_source_ref_uniq" ON "site_locations" USING btree ("partner_id","source_ref") WHERE "site_locations"."source_ref" IS NOT NULL;
CREATE UNIQUE INDEX "site_work_assignments_vendor_work_type_site_unique" ON "site_work_assignments" USING btree ("vendor_id","work_type_id","site_location_id");
CREATE UNIQUE INDEX "ticket_crew_ticket_employee_active_idx" ON "ticket_crew" USING btree ("ticket_id","employee_id") WHERE removed_at IS NULL;
CREATE UNIQUE INDEX "ticket_sched_notif_ticket_user_kind_idx" ON "ticket_scheduled_notifications" USING btree ("ticket_id","user_id","kind");
CREATE UNIQUE INDEX "uniq_ticket_assignment_rate" ON "ticket_assignment_rates" USING btree ("ticket_id","employee_id");
CREATE UNIQUE INDEX "user_org_memberships_user_partner_unique" ON "user_org_memberships" USING btree ("user_id","partner_id");
CREATE UNIQUE INDEX "user_org_memberships_user_vendor_unique" ON "user_org_memberships" USING btree ("user_id","vendor_id");
CREATE INDEX "user_org_memberships_user_idx" ON "user_org_memberships" USING btree ("user_id");
CREATE INDEX "user_org_memberships_org_idx" ON "user_org_memberships" USING btree ("org_type","partner_id","vendor_id");
CREATE INDEX "notifications_user_idx" ON "notifications" USING btree ("user_id");
CREATE UNIQUE INDEX "notifications_user_dedupe_unique" ON "notifications" USING btree ("user_id","dedupe_key");
CREATE INDEX "notifications_unemailed_idx" ON "notifications" USING btree ("user_id","created_at") WHERE "notifications"."emailed_at" is null;
CREATE UNIQUE INDEX "vendor_ratings_ticket_unique" ON "vendor_ratings" USING btree ("ticket_id") WHERE "vendor_ratings"."ticket_id" IS NOT NULL;
CREATE UNIQUE INDEX "vendor_ratings_vendor_partner_standalone_unique" ON "vendor_ratings" USING btree ("vendor_id","partner_id") WHERE "vendor_ratings"."ticket_id" IS NULL;
CREATE UNIQUE INDEX "location_consents_user_device_uniq" ON "location_consents" USING btree ("user_id","device_id");
CREATE INDEX "guest_sessions_expires_idx" ON "guest_sessions" USING btree ("expires_at");
CREATE INDEX "site_visits_site_idx" ON "site_visits" USING btree ("site_location_id");