ALTER TABLE "site_visits" ADD CONSTRAINT "site_visits_guest_session_id_guest_sessions_id_fk" FOREIGN KEY ("guest_session_id") REFERENCES "public"."guest_sessions"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "site_visits" ADD CONSTRAINT "site_visits_host_partner_id_partners_id_fk" FOREIGN KEY ("host_partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "site_visits" ADD CONSTRAINT "site_visits_host_vendor_id_vendors_id_fk" FOREIGN KEY ("host_vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "vendor_partner_billing_settings" ADD CONSTRAINT "vendor_partner_billing_settings_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "vendor_partner_billing_settings" ADD CONSTRAINT "vendor_partner_billing_settings_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_ticket_links" ADD CONSTRAINT "invoice_ticket_links_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_ticket_links" ADD CONSTRAINT "invoice_ticket_links_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_rate_card_snapshots" ADD CONSTRAINT "invoice_rate_card_snapshots_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_rate_card_snapshots" ADD CONSTRAINT "invoice_rate_card_snapshots_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_payment_audit_log" ADD CONSTRAINT "invoice_payment_audit_log_payment_id_invoice_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."invoice_payments"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_payment_audit_log" ADD CONSTRAINT "invoice_payment_audit_log_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_payment_audit_log" ADD CONSTRAINT "invoice_payment_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_payments" ADD CONSTRAINT "invoice_payments_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_payments" ADD CONSTRAINT "invoice_payments_recorded_by_user_id_users_id_fk" FOREIGN KEY ("recorded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_payments" ADD CONSTRAINT "invoice_payments_voided_by_user_id_users_id_fk" FOREIGN KEY ("voided_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_credit_memos" ADD CONSTRAINT "invoice_credit_memos_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_credit_memos" ADD CONSTRAINT "invoice_credit_memos_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_backfill_audit_log" ADD CONSTRAINT "invoice_line_category_backfill_audit_log_line_id_invoice_lines_id_fk" FOREIGN KEY ("line_id") REFERENCES "public"."invoice_lines"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_backfill_audit_log" ADD CONSTRAINT "invoice_line_category_backfill_audit_log_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_backfill_audit_log" ADD CONSTRAINT "invoice_line_category_backfill_audit_log_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_backfill_audit_log" ADD CONSTRAINT "invoice_line_category_backfill_audit_log_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_backfill_audit_log" ADD CONSTRAINT "invoice_line_category_backfill_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_audit" ADD CONSTRAINT "invoice_line_category_audit_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_audit" ADD CONSTRAINT "invoice_line_category_audit_line_id_invoice_lines_id_fk" FOREIGN KEY ("line_id") REFERENCES "public"."invoice_lines"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_audit" ADD CONSTRAINT "invoice_line_category_audit_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_audit" ADD CONSTRAINT "invoice_line_category_audit_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_line_category_audit" ADD CONSTRAINT "invoice_line_category_audit_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_send_log" ADD CONSTRAINT "invoice_send_log_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_send_log" ADD CONSTRAINT "invoice_send_log_sent_by_user_id_users_id_fk" FOREIGN KEY ("sent_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "invoice_reminder_log" ADD CONSTRAINT "invoice_reminder_log_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoice_reminder_log" ADD CONSTRAINT "invoice_reminder_log_sent_by_user_id_users_id_fk" FOREIGN KEY ("sent_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "payment_audit" ADD CONSTRAINT "payment_audit_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payment_audit" ADD CONSTRAINT "payment_audit_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "report_export_audit_log" ADD CONSTRAINT "report_export_audit_log_downloaded_by_user_id_users_id_fk" FOREIGN KEY ("downloaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "reconciliation_weekly_recap_log" ADD CONSTRAINT "reconciliation_weekly_recap_log_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "vendor_merge_audit_log" ADD CONSTRAINT "vendor_merge_audit_log_survivor_vendor_id_vendors_id_fk" FOREIGN KEY ("survivor_vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "vendor_merge_audit_log" ADD CONSTRAINT "vendor_merge_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "vendor_merge_audit_log" ADD CONSTRAINT "vendor_merge_audit_log_reverted_by_user_id_users_id_fk" FOREIGN KEY ("reverted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "site_location_admin_audit_log" ADD CONSTRAINT "site_location_admin_audit_log_site_location_id_site_locations_id_fk" FOREIGN KEY ("site_location_id") REFERENCES "public"."site_locations"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "site_location_admin_audit_log" ADD CONSTRAINT "site_location_admin_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "schedule_cert_override_audit_log" ADD CONSTRAINT "schedule_cert_override_audit_log_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "schedule_cert_override_audit_log" ADD CONSTRAINT "schedule_cert_override_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping" ADD CONSTRAINT "qb_account_mapping_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "qb_account_mapping" ADD CONSTRAINT "qb_account_mapping_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "qb_account_mapping_audit_log" ADD CONSTRAINT "qb_account_mapping_audit_log_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping_audit_log" ADD CONSTRAINT "qb_account_mapping_audit_log_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping_audit_log" ADD CONSTRAINT "qb_account_mapping_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping_bulk_actions" ADD CONSTRAINT "qb_account_mapping_bulk_actions_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping_bulk_actions" ADD CONSTRAINT "qb_account_mapping_bulk_actions_undone_by_user_id_users_id_fk" FOREIGN KEY ("undone_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "qb_account_mapping_cleanup_audit" ADD CONSTRAINT "qb_account_mapping_cleanup_audit_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "tax_1099_filings" ADD CONSTRAINT "tax_1099_filings_payer_partner_id_partners_id_fk" FOREIGN KEY ("payer_partner_id") REFERENCES "public"."partners"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "tax_1099_filings" ADD CONSTRAINT "tax_1099_filings_recipient_vendor_id_vendors_id_fk" FOREIGN KEY ("recipient_vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "tax_1099_filings" ADD CONSTRAINT "tax_1099_filings_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "tax_1099_correction_audit_log" ADD CONSTRAINT "tax_1099_correction_audit_log_filing_id_tax_1099_filings_id_fk" FOREIGN KEY ("filing_id") REFERENCES "public"."tax_1099_filings"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "tax_1099_correction_audit_log" ADD CONSTRAINT "tax_1099_correction_audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
CREATE UNIQUE INDEX "acct_conn_items_conn_line_uniq" ON "accounting_connection_items" USING btree ("connection_id","line_type");
CREATE INDEX "accounting_conn_reminder_log_conn_idx" ON "accounting_connection_reminder_log" USING btree ("connection_id");
CREATE UNIQUE INDEX "accounting_conn_reminder_log_dedupe_unique" ON "accounting_connection_reminder_log" USING btree ("dedupe_key");
CREATE UNIQUE INDEX "accounting_conn_vendor_provider_uniq" ON "accounting_connections" USING btree ("vendor_id","provider");
CREATE INDEX "accounting_conn_status_idx" ON "accounting_connections" USING btree ("status");
CREATE UNIQUE INDEX "accounting_pushed_invoices_uniq" ON "accounting_pushed_invoices" USING btree ("vendor_id","provider","invoice_number");
CREATE INDEX "ap_payment_digest_log_partner_idx" ON "ap_payment_digest_log" USING btree ("partner_id");
CREATE UNIQUE INDEX "ap_payment_digest_log_dedupe_unique" ON "ap_payment_digest_log" USING btree ("dedupe_key");
CREATE INDEX "assistant_conversations_user_idx" ON "assistant_conversations" USING btree ("user_id","updated_at");
CREATE INDEX "assistant_messages_conv_idx" ON "assistant_messages" USING btree ("conversation_id","created_at");
CREATE INDEX "certification_reminder_log_cert_idx" ON "certification_reminder_log" USING btree ("certification_id");
CREATE UNIQUE INDEX "certification_reminder_log_dedupe_unique" ON "certification_reminder_log" USING btree ("dedupe_key");
CREATE UNIQUE INDEX "comment_read_receipts_uniq" ON "comment_read_receipts" USING btree ("source","comment_id","user_id");
CREATE INDEX "dashboard_1099_delivery_jobs_scope_idx" ON "dashboard_1099_delivery_jobs" USING btree ("scope","partner_id","created_at");
CREATE INDEX "dashboard_1099_delivery_jobs_status_idx" ON "dashboard_1099_delivery_jobs" USING btree ("status");
CREATE INDEX "dashboard_1099_email_log_scope_idx" ON "dashboard_1099_email_log" USING btree ("scope","partner_id","sent_at");
CREATE UNIQUE INDEX "dashboard_1099_email_log_dedupe_unique" ON "dashboard_1099_email_log" USING btree ("dedupe_key");
CREATE UNIQUE INDEX "dashboard_1099_email_settings_admin_unique" ON "dashboard_1099_email_settings" USING btree ("scope") WHERE "dashboard_1099_email_settings"."scope" = 'admin';
CREATE UNIQUE INDEX "dashboard_1099_email_settings_partner_unique" ON "dashboard_1099_email_settings" USING btree ("partner_id") WHERE "dashboard_1099_email_settings"."scope" = 'partner' and "dashboard_1099_email_settings"."partner_id" is not null;
CREATE INDEX "dashboard_1099_email_settings_enabled_idx" ON "dashboard_1099_email_settings" USING btree ("enabled");
CREATE UNIQUE INDEX "demo_user_label_overrides_username_locale_unique" ON "demo_user_label_overrides" USING btree ("username","locale");
CREATE INDEX "direct_assignments_vendor_status_idx" ON "direct_assignments" USING btree ("vendor_id","status");
CREATE INDEX "direct_assignments_partner_status_idx" ON "direct_assignments" USING btree ("partner_id","status");
CREATE INDEX "direct_assignments_site_idx" ON "direct_assignments" USING btree ("site_location_id");
CREATE INDEX "field_push_tokens_user_idx" ON "field_push_tokens" USING btree ("user_id");
CREATE INDEX "fire_transmitter_settings_audit_created_idx" ON "fire_transmitter_settings_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "onboarding_progress_partner_uniq" ON "onboarding_progress" USING btree ("partner_id");
CREATE UNIQUE INDEX "onboarding_progress_vendor_uniq" ON "onboarding_progress" USING btree ("vendor_id");
CREATE UNIQUE INDEX "onboarding_progress_vendor_people_uniq" ON "onboarding_progress" USING btree ("vendor_people_id");
CREATE UNIQUE INDEX "partners_canonical_name_unique" ON "partners" USING btree (lower(btrim("name")));
CREATE INDEX "platform_settings_audit_field_created_idx" ON "platform_settings_audit_log" USING btree ("field","created_at");
CREATE UNIQUE INDEX "vendors_canonical_name_unique" ON "vendors" USING btree (lower(btrim("name")));
CREATE UNIQUE INDEX "work_types_canonical_name_unique" ON "work_types" USING btree (lower(btrim("name")));
CREATE UNIQUE INDEX "vendor_work_types_vendor_work_type_unique" ON "vendor_work_types" USING btree ("vendor_id","work_type_id");
CREATE UNIQUE INDEX "vendor_catalog_versions_vendor_version_unique" ON "vendor_catalog_versions" USING btree ("vendor_id","version");
CREATE INDEX "vendor_catalog_versions_vendor_idx" ON "vendor_catalog_versions" USING btree ("vendor_id");
CREATE INDEX "partner_eula_acceptances_pair_idx" ON "partner_eula_acceptances" USING btree ("partner_id","vendor_id","vendor_catalog_version_id");
CREATE INDEX "partner_vendor_approval_events_pair_idx" ON "partner_vendor_approval_events" USING btree ("partner_id","vendor_id","created_at");
CREATE INDEX "partner_vendor_approval_events_vendor_idx" ON "partner_vendor_approval_events" USING btree ("vendor_id");
CREATE UNIQUE INDEX "work_type_site_location_unique" ON "work_type_site_locations" USING btree ("work_type_id","site_location_id");
CREATE UNIQUE INDEX "partner_work_type_afe_unique" ON "partner_work_type_afes" USING btree ("partner_id","work_type_id");
CREATE UNIQUE INDEX "partner_vendor_work_type_approval_unique" ON "partner_vendor_work_type_approvals" USING btree ("partner_id","vendor_id","work_type_id");
CREATE UNIQUE INDEX "partner_vendor_relationship_unique" ON "partner_vendor_relationships" USING btree ("partner_id","vendor_id");
CREATE UNIQUE INDEX "vendor_site_location_afe_unique" ON "vendor_site_location_afes" USING btree ("vendor_id","site_location_id");
CREATE UNIQUE INDEX "site_locations_partner_source_ref_uniq" ON "site_locations" USING btree ("partner_id","source_ref") WHERE "site_locations"."source_ref" IS NOT NULL;
CREATE UNIQUE INDEX "site_work_assignments_vendor_work_type_site_unique" ON "site_work_assignments" USING btree ("vendor_id","work_type_id","site_location_id");
CREATE UNIQUE INDEX "ticket_crew_ticket_employee_active_idx" ON "ticket_crew" USING btree ("ticket_id","employee_id") WHERE removed_at IS NULL;
CREATE UNIQUE INDEX "ticket_sched_notif_ticket_user_kind_idx" ON "ticket_scheduled_notifications" USING btree ("ticket_id","user_id","kind");
CREATE UNIQUE INDEX "uniq_ticket_assignment_rate" ON "ticket_assignment_rates" USING btree ("ticket_id","employee_id");
CREATE UNIQUE INDEX "user_org_memberships_user_partner_unique" ON "user_org_memberships" USING btree ("user_id","partner_id");
CREATE UNIQUE INDEX "user_org_memberships_user_vendor_unique" ON "user_org_memberships" USING btree ("user_id","vendor_id");
CREATE INDEX "user_org_memberships_user_idx" ON "user_org_memberships" USING btree ("user_id");
CREATE INDEX "user_org_memberships_org_idx" ON "user_org_memberships" USING btree ("org_type","partner_id","vendor_id");
CREATE INDEX "notifications_user_idx" ON "notifications" USING btree ("user_id");
CREATE UNIQUE INDEX "notifications_user_dedupe_unique" ON "notifications" USING btree ("user_id","dedupe_key");
CREATE INDEX "notifications_unemailed_idx" ON "notifications" USING btree ("user_id","created_at") WHERE "notifications"."emailed_at" is null;
CREATE UNIQUE INDEX "vendor_ratings_ticket_unique" ON "vendor_ratings" USING btree ("ticket_id") WHERE "vendor_ratings"."ticket_id" IS NOT NULL;
CREATE UNIQUE INDEX "vendor_ratings_vendor_partner_standalone_unique" ON "vendor_ratings" USING btree ("vendor_id","partner_id") WHERE "vendor_ratings"."ticket_id" IS NULL;
CREATE UNIQUE INDEX "location_consents_user_device_uniq" ON "location_consents" USING btree ("user_id","device_id");
CREATE INDEX "guest_sessions_expires_idx" ON "guest_sessions" USING btree ("expires_at");
CREATE INDEX "site_visits_site_idx" ON "site_visits" USING btree ("site_location_id");
CREATE INDEX "site_visits_active_idx" ON "site_visits" USING btree ("site_location_id","check_out_time");
CREATE INDEX "site_visits_host_partner_idx" ON "site_visits" USING btree ("host_partner_id");
CREATE INDEX "site_visits_host_vendor_idx" ON "site_visits" USING btree ("host_vendor_id");
CREATE UNIQUE INDEX "vp_billing_settings_unique" ON "vendor_partner_billing_settings" USING btree ("vendor_id","partner_id");
CREATE UNIQUE INDEX "invoices_invoice_number_unique" ON "invoices" USING btree ("invoice_number");
CREATE INDEX "invoices_vendor_status_idx" ON "invoices" USING btree ("vendor_id","status");
CREATE INDEX "invoices_partner_status_idx" ON "invoices" USING btree ("partner_id","status");
CREATE INDEX "invoices_open_period_idx" ON "invoices" USING btree ("vendor_id","partner_id","cadence","status","period_start");
CREATE UNIQUE INDEX "invoices_unique_draft_per_period" ON "invoices" USING btree ("vendor_id","partner_id","cadence","period_start") WHERE status = 'draft' AND supplemental_of_invoice_id IS NULL AND cadence <> 'per_ticket';
CREATE UNIQUE INDEX "invoices_unique_supplemental_draft_per_period" ON "invoices" USING btree ("vendor_id","partner_id","cadence","period_start","supplemental_of_invoice_id") WHERE status = 'draft' AND supplemental_of_invoice_id IS NOT NULL AND cadence <> 'per_ticket';
CREATE INDEX "invoice_lines_invoice_idx" ON "invoice_lines" USING btree ("invoice_id");
CREATE INDEX "invoice_lines_ticket_idx" ON "invoice_lines" USING btree ("ticket_id");
CREATE INDEX "invoice_lines_source_idx" ON "invoice_lines" USING btree ("source_type","source_id");
CREATE UNIQUE INDEX "invoice_lines_generated_dedupe_uniq" ON "invoice_lines" USING btree ("invoice_id","ticket_id","source_type","source_id") WHERE is_manual_override = false AND ticket_id IS NOT NULL AND source_id IS NOT NULL;
CREATE UNIQUE INDEX "invoice_lines_generated_dedupe_null_source_uniq" ON "invoice_lines" USING btree ("invoice_id","ticket_id","source_type") WHERE is_manual_override = false AND ticket_id IS NOT NULL AND source_id IS NULL;
CREATE UNIQUE INDEX "invoice_ticket_link_unique" ON "invoice_ticket_links" USING btree ("invoice_id","ticket_id");
CREATE INDEX "invoice_ticket_link_ticket_idx" ON "invoice_ticket_links" USING btree ("ticket_id");
CREATE INDEX "invoice_rate_card_snapshot_invoice_idx" ON "invoice_rate_card_snapshots" USING btree ("invoice_id","captured_at");
CREATE INDEX "invoice_payment_audit_log_payment_idx" ON "invoice_payment_audit_log" USING btree ("payment_id");
CREATE INDEX "invoice_payment_audit_log_invoice_idx" ON "invoice_payment_audit_log" USING btree ("invoice_id");
CREATE INDEX "invoice_payments_invoice_idx" ON "invoice_payments" USING btree ("invoice_id");
CREATE INDEX "invoice_payments_paid_at_idx" ON "invoice_payments" USING btree ("paid_at");
CREATE INDEX "invoice_credit_memos_invoice_idx" ON "invoice_credit_memos" USING btree ("invoice_id");
CREATE INDEX "invoice_line_cat_backfill_audit_run_idx" ON "invoice_line_category_backfill_audit_log" USING btree ("run_id","id");
CREATE INDEX "invoice_line_cat_backfill_audit_created_idx" ON "invoice_line_category_backfill_audit_log" USING btree ("created_at");
CREATE INDEX "invoice_line_cat_backfill_audit_vendor_idx" ON "invoice_line_category_backfill_audit_log" USING btree ("vendor_id","created_at");
CREATE INDEX "invoice_line_cat_backfill_audit_partner_idx" ON "invoice_line_category_backfill_audit_log" USING btree ("partner_id","created_at");
CREATE INDEX "invoice_line_cat_audit_vendor_idx" ON "invoice_line_category_audit" USING btree ("vendor_id","created_at");
CREATE INDEX "invoice_line_cat_audit_partner_idx" ON "invoice_line_category_audit" USING btree ("partner_id","created_at");
CREATE INDEX "invoice_line_cat_audit_created_idx" ON "invoice_line_category_audit" USING btree ("created_at");
CREATE INDEX "invoice_line_cat_audit_batch_idx" ON "invoice_line_category_audit" USING btree ("batch_id");
CREATE INDEX "invoice_send_log_invoice_idx" ON "invoice_send_log" USING btree ("invoice_id");
CREATE INDEX "invoice_reminder_log_invoice_idx" ON "invoice_reminder_log" USING btree ("invoice_id");
CREATE UNIQUE INDEX "invoice_reminder_log_dedupe_unique" ON "invoice_reminder_log" USING btree ("dedupe_key");
CREATE INDEX "payment_audit_ticket_idx" ON "payment_audit" USING btree ("ticket_id","created_at");
CREATE INDEX "payment_audit_created_idx" ON "payment_audit" USING btree ("created_at");
CREATE INDEX "report_export_audit_kind_idx" ON "report_export_audit_log" USING btree ("report_kind","created_at");
CREATE INDEX "report_export_audit_user_idx" ON "report_export_audit_log" USING btree ("downloaded_by_user_id","created_at");
CREATE INDEX "report_export_audit_created_idx" ON "report_export_audit_log" USING btree ("created_at");
CREATE INDEX "report_export_audit_retried_from_idx" ON "report_export_audit_log" USING btree ((("scope"->>'retriedFromAuditId')::int)) WHERE "report_export_audit_log"."scope"->>'retriedFromAuditId' ~ '^[0-9]+$';
CREATE INDEX "reconciliation_weekly_recap_log_vendor_idx" ON "reconciliation_weekly_recap_log" USING btree ("vendor_id");
CREATE UNIQUE INDEX "reconciliation_weekly_recap_log_dedupe_unique" ON "reconciliation_weekly_recap_log" USING btree ("dedupe_key");
CREATE INDEX "vendor_merge_audit_survivor_idx" ON "vendor_merge_audit_log" USING btree ("survivor_vendor_id","created_at");
CREATE INDEX "vendor_merge_audit_created_idx" ON "vendor_merge_audit_log" USING btree ("created_at");
CREATE INDEX "site_location_admin_audit_site_idx" ON "site_location_admin_audit_log" USING btree ("site_location_id","created_at");
CREATE INDEX "site_location_admin_audit_created_idx" ON "site_location_admin_audit_log" USING btree ("created_at");
CREATE INDEX "schedule_cert_override_audit_ticket_idx" ON "schedule_cert_override_audit_log" USING btree ("ticket_id","created_at");
CREATE INDEX "schedule_cert_override_audit_created_idx" ON "schedule_cert_override_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "qb_account_mapping_scope_line_type" ON "qb_account_mapping" USING btree ("vendor_id","partner_id","line_type");
CREATE INDEX "qb_account_mapping_audit_created_idx" ON "qb_account_mapping_audit_log" USING btree ("created_at");
CREATE INDEX "qb_account_mapping_audit_line_type_idx" ON "qb_account_mapping_audit_log" USING btree ("line_type","created_at");
CREATE INDEX "qb_account_mapping_audit_vendor_idx" ON "qb_account_mapping_audit_log" USING btree ("vendor_id","created_at");
CREATE INDEX "qb_account_mapping_audit_partner_idx" ON "qb_account_mapping_audit_log" USING btree ("partner_id","created_at");
CREATE INDEX "qb_account_mapping_audit_actor_idx" ON "qb_account_mapping_audit_log" USING btree ("actor_user_id","created_at");
CREATE INDEX "qb_account_mapping_bulk_actions_created_idx" ON "qb_account_mapping_bulk_actions" USING btree ("created_at");
CREATE INDEX "qb_account_mapping_cleanup_audit_created_idx" ON "qb_account_mapping_cleanup_audit" USING btree ("created_at");
CREATE UNIQUE INDEX "tax_1099_filings_unique" ON "tax_1099_filings" USING btree ("tax_year","form_type","payer_partner_id","recipient_vendor_id");
CREATE INDEX "tax_1099_filings_year_idx" ON "tax_1099_filings" USING btree ("tax_year","form_type");
CREATE INDEX "tax_1099_filings_payer_idx" ON "tax_1099_filings" USING btree ("payer_partner_id","tax_year");
CREATE INDEX "tax_1099_filings_sendgrid_msg_idx" ON "tax_1099_filings" USING btree ("sendgrid_message_id");
CREATE INDEX "tax_1099_correction_audit_filing_idx" ON "tax_1099_correction_audit_log" USING btree ("filing_id","created_at");
CREATE INDEX "tax_1099_correction_audit_created_idx" ON "tax_1099_correction_audit_log" USING btree ("created_at");
CREATE UNIQUE INDEX "signup_assistant_counters_ns_key_uniq" ON "signup_assistant_counters" USING btree ("namespace","key");